name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Create fresh Flutter project structure
        run: flutter create . --org Vibra.Kirci --project-name vibrachat --platforms=android
      - name: Restore user files
        run: |
          mkdir -p android/app/
          # Zaten yüklediğimiz dosyaları yerine koyuyoruz
          if [ -f "backup_google-services.json" ]; then cp backup_google-services.json android/app/google-services.json; fi
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
